[package]
name = "attach-iface"
version = "0.1.0"
authors = ["Nick Hynes <nhynes@oasislabs.com>"]
edition = "2018"

[dependencies]
oasis-rpc = { version = "0.1", features = ["saveload"] }
serde = "1.0"
serde_json = "1.0"
walrus = "0.8"
